name: Get runner image

on:
  workflow_call:
    outputs:
      runs-on:
        description: "Get first occurence of build-on base as image runner"
        value: ${{ jobs.get-runner-image.outputs.runs-on }}

jobs:
  get-runner-image:
    name: Get runner image
    runs-on: ubuntu-22.04
    outputs:
      runs-on: ${{ env.BUILD_ON }}
    steps:
      - uses: actions/checkout@v3
      - name: Get build-on and run-on values
        run: |
          echo "BUILD_ON=$(yq '[.bases.[].build-on.[0].name, .bases.[].build-on.[0].channel] | join("-")' charmcraft.yaml)" >> $GITHUB_ENV

