name: Release charm to a branch in channel edge

on:
  workflow_call:
    inputs:
      integration-test-extra-arguments:
        description: Additional arguments to pass to the integration tests
        type: string
      integration-test-pre-run-script:
        description: Path to the bash script to be run before the integration tests
        type: string
      integration-test-provider:
        description: Actions operator provider for the integration tests as per https://github.com/charmed-kubernetes/actions-operator#usage
        type: string
      integration-test-series:
        description: List of series to run the integration tests in JSON format, i.e. '["jammy", "focal"]'. Each element will be passed to tox as --series argument
        type: string
        default: '[""]'
      test-runs-on:
        description: Runner image for the tests
        type: string
        default: ubuntu-20.04

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@1.0.3
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  tests:
    name: Run tests
    uses: ./.github/workflows/test.yaml
    with:
      runs-on: ${{ inputs.test-runs-on }}
  integration-tests:
    name: Run integration tests
    uses: ./.github/workflows/integration_test.yaml
    with:
      extra-arguments: ${{ inputs.integration-test-extra-arguments }}
      pre-run-script: ${{ integration-test-pre-run-script }}
      provider: ${{ inputs.integration-test-provider }}
      runs-on: ${{ inputs.test-runs-on }}
      series: ${{ inputs.integration-test-series }}
  select-branch:
    name: Select target branch
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ env.branch }}
    steps:
      - name: Get target branch
        id: extract-branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
  publish-charm:
    name: Publish
    uses: ./.github/workflows/publish_charm.yaml
    needs: [ tests, integration-tests, select-branch ]
    with:
      channel: ${{ needs.select-branch.outputs.branch }}
      images: ${{ needs.integration-tests.outputs.images }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
