name: Promote charm

on:
  workflow_call:
    inputs:
      origin-channel:
        type: string
        description: 'Origin Channel'
      destination-channel:
        type: string
        description: 'Destination Channel'

jobs:
  get-runner-image:
    name: Get runner image
    runs-on: ubuntu-22.04
    outputs:
      runs-on: ${{ env.BUILD_ON }}
    steps:
      - uses: actions/checkout@v3
      - name: Get build-on and run-on values
        run: |
          echo "BUILD_ON=$(yq '[.bases.[].build-on.[].name, .bases.[].build-on.[].channel] | join("-")' charmcraft.yaml" >> $GITHUB_ENV
  promote-charm:
    name: Promote charm
    runs-on: ${{ needs.get-runner-image.outputs.runs-on }}
    needs: get-runner-image
    steps:
      - uses: actions/checkout@v3
      - name: Release charm to channel
        uses: canonical/charming-actions/release-charm@2.1.1
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          origin-channel: ${{ github.event.inputs.origin-channel }}
          destination-channel: ${{ github.event.inputs.destination-channel }}
