name: Promote charm

on:
  workflow_call:
    inputs:
      origin-channel:
        type: string
        description: 'Origin Channel'
      destination-channel:
        type: string
        description: 'Destination Channel'
    secrets:
      CHARMHUB-TOKEN:
        required: true
      GITHUB-TOKEN:
        required: true

jobs:
  promote-charm:
    name: Promote charm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release charm to channel
        uses: canonical/charming-actions/release-charm@2.1.1
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          origin-channel: ${{ github.event.inputs.origin-channel }}
          destination-channel: ${{ github.event.inputs.destination-channel }}
